spring:
  application:
    name: Exam Service
  main:
    allow-bean-definition-overriding: true
    problemdetails:
      enabled: true
  jpa:
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.sample.doping.configuration.CustomPhysicalNamingStrategy
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/doping?createDatabaseIfNotExist=true?useUnicode=yes&characterEncoding=UTF-8
    username: bilal.say
    password: Pazar2024
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 100
      idle-timeout: 30000
      pool-name: myapi
      max-lifetime: 2000000
      connection-timeout: 30000
    type: com.zaxxer.hikari.HikariDataSource

server:
  port: 8080

couchbase:
  properties:
    username: Administrator
    password: admin1
    connection-string: couchbase://127.0.0.1
    bucket-name: doping
    scope-name: exam
    cacheable-collection: cache-collection
